version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda"
s3_bucket = "aws-sam-cli-managed-default-west-1"
s3_prefix = "gh-lambda"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []