name: Lambda duild/deploy Pipeline

env:
  APP_VERSION: '0.0.1'
  BRANCH: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
on: [push, pull_request]
jobs:
  build-lambda-layer:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps: 
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          filters: |
            layer: 
              - './src/layers/**'
      - uses: actions/setup-python@v2
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - name: Check changes on the layer
        if: ${{ steps.changes.outputs.layer == 'true' }}
        run: echo "github.head_ref ---> ${{ github.head_ref }}  "
      - name: Output the branch name
        run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)

  unit-testing:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: build-lambda-layer
    steps: 
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          filters: |
            lambda1: 
              - './src/lambda/**' 
      - uses: actions/setup-python@v2

      - name: build using SAM KPI VIEW quarterly
        if: ${{ steps.changes.outputs.lambda1 == 'true' }}
        run: echo "+++++++> Build lambda "
      - name: deploy on AWS
        if: ${{ steps.changes.outputs.lambda1 == 'true' }}
        run: echo "+++++++> Deploy lambda "

  deploy-lambda:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: unit-testing
    steps: 
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          filters: |
            lambda1: 
              - './src/lambda/**' 
      - uses: actions/setup-python@v2

      - name: build using SAM KPI VIEW quarterly
        if: ${{ steps.changes.outputs.lambda1 == 'true' }}
        run: echo "+++++++> Build lambda "
      - name: deploy on AWS
        if: ${{ steps.changes.outputs.lambda1 == 'true' }}
        run: echo "+++++++> Deploy lambda "


